name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Unzip project
      run: unzip CushionTrainer_AndroidProject.zip -d app

    - name: Build APK
      run: |
        cd app
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: CushionTrainer-APK
        path: app/app/build/outputs/apk/debug/app-debug.apk
